CREATE TABLE IF NOT EXISTS "users"(
	id SERIAL PRIMARY KEY,
	userid INT UNIQUE,
	password varchar(80),
	nickname VARCHAR(40),
	nickname_iv VARCHAR(80),
	birth_day INT,
	birth_day_iv VARCHAR(80),
	birth_month INT,
	birth_month_iv VARCHAR(80),
	birth_year int,
	birth_year_iv VARCHAR(80),
	gender VARCHAR(20),
	gender_iv varchar(80),
	height int,
	height_iv varchar(80),
	weight int,
	weight_iv varchar(80),
	religion VARCHAR(80),
	religion_iv varchar(80),
	sexuality VARCHAR(80),
	sexuality_iv varchar(80),
	race varchar(80),
	race_iv varchar(80),
	grade int,
	grade_iv varchar(80),
	postal_code varchar(10),
	postal_code_iv varchar(80),
	avatar_string varchar(10),
	avatar_string_iv varchar(80),
	events int[],
	events_iv varchar(80)[],
	surveys int[],
	surveys_iv varchar(80)[]
);